## 회귀모델 사용
- y(label, 종속변수, target)가 연속형일 때 사용 # label, 종속변수, target는 y의 명칭들

In [26]:
import sklearn as sk

# datasets는 Scikit-learn에 내장된 다양한 샘플 데이터셋을 제공하는 모듈입니다.
# 여기서 load_diabetes는 당뇨병과 관련된 데이터셋을 가져오는 함수입니다.

### 데이터 수집

In [27]:
from sklearn import datasets

#from boston house
# datasets.load_diabetes() 
load_diabetes = datasets.load_diabetes() # 인디언 당뇨 상황 조사
load_diabetes
load_diabetes.keys() # 딕셔너리의 형태로 어떠한 key 가 들어있는지 확인

# datasets.load_diabetes()는 당뇨병과 관련된 의료 데이터를 불러옵니다.
# 이 데이터셋은 당뇨병을 예측하기 위한 **독립 변수(특성)**와 실제 **결과값(타겟)**을 포함하고 있습니다.
# 데이터는 딕셔너리(키-값 형태)로 저장됩니다. keys()는 데이터셋이 가진 주요 정보를 확인할 수 있는 열쇠(key)를 반환합니다.
# 반환되는 주요 키는 다음과 같습니다:
# 'data': 특성(feature) 데이터
# 'target': 예측해야 할 값(레이블 데이터)
# 'feature_names': 특성의 이름
# 'DESCR': 데이터셋 설명
# 'frame': 데이터프레임 (일부 데이터셋만)
# 'filename': 데이터셋 파일 경로

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [28]:
# feature datas 
type(load_diabetes['data']), load_diabetes['data'].shape #shape 데이터의 크기 확인

# load_diabetes['data']는 특성 데이터를 담고 있습니다.
# 이 데이터를 탐색하며:
# type: 데이터의 자료형을 확인합니다. (예: numpy.ndarray는 배열 형태)
# shape: 데이터의 크기를 확인합니다. 예를 들어 (442, 10)이라면:
# **442개의 샘플(행)**과 **10개의 특성(열)**이 있다는 뜻입니다.

(numpy.ndarray, (442, 10))

In [29]:
# label data
type(load_diabetes['target']), load_diabetes['target'].shape, load_diabetes['target'].dtype

# load_diabetes['target']는 우리가 예측하고자 하는 값(레이블 데이터)을 저장합니다.
# 레이블 데이터의 정보를 확인하며:
# type: 자료형(배열 형태인지 확인)
# shape: 몇 개의 레이블이 있는지 확인
# dtype: 데이터가 어떤 유형(정수/실수 등)인지 확인합니다.

(numpy.ndarray, (442,), dtype('float64'))

In [30]:
# feature names
type(load_diabetes['feature_names']), load_diabetes['feature_names'], len(load_diabetes['feature_names'])

# load_diabetes['feature_names']는 각 특성의 이름을 제공합니다.
# 예시: ['age', 'sex', 'bmi', 'bp', ...]
# len(load_diabetes['feature_names'])를 통해 특성의 개수를 확인할 수 있습니다.


(list, ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], 10)

In [31]:
print(load_diabetes.DESCR)

# DESCR는 데이터셋에 대한 설명 문서입니다.
# 데이터셋의 출처, 구성, 각 특성이 의미하는 바 등을 설명합니다.

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

### 데이터 전처리
- 결측치와 이상치 처리
- 데이터셋 분할(학습용도와 검증용도)

In [32]:
import pandas as pd

In [33]:
# feature 처리
df_diabetes = pd.DataFrame(data = load_diabetes['data']
             , columns = load_diabetes['feature_names'])
df_diabetes.head(3)

# pd.DataFrame을 사용하여 데이터를 표(테이블) 형식으로 변환합니다.
# data=load_diabetes['data']: 데이터셋의 특성 데이터를 사용합니다.
# columns=load_diabetes['feature_names']: 각 열(특성)에 이름을 붙입니다.
# head(3): 테이블의 첫 3줄을 출력해 데이터의 구조를 확인합니다.

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930

In [34]:
# label 처리
df_diabetes['MeasureValue'] = load_diabetes['target']

# load_diabetes['target']: 우리가 예측하고자 하는 값(레이블 데이터)을 가져옵니다.
# 새 열(컬럼)을 추가해 **'MeasureValue'**라는 이름으로 레이블 데이터를 추가합니다.


In [35]:
df_diabetes.head(3)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   

         s4        s5        s6  MeasureValue  
0 -0.002592  0.019907 -0.017646         151.0  
1 -0.039493 -0.068332 -0.092204          75.0  
2 -0.002592  0.002861 -0.025930         141.0

In [36]:
df_diabetes.shape

(442, 11)

In [37]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   age           442 non-null    float64
 1   sex           442 non-null    float64
 2   bmi           442 non-null    float64
 3   bp            442 non-null    float64
 4   s1            442 non-null    float64
 5   s2            442 non-null    float64
 6   s3            442 non-null    float64
 7   s4            442 non-null    float64
 8   s5            442 non-null    float64
 9   s6            442 non-null    float64
 10  MeasureValue  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB


In [38]:
# 학습용도와 검증용도 분할

### 데이터 학습 과정

In [39]:
from sklearn.linear_model import LinearRegression
linearRegression = LinearRegression()
linearRegression

# LinearRegression()은 Scikit-learn의 선형 회귀 클래스입니다.
# 이 코드는 선형 회귀 모델을 초기화한 것입니다. 아직 데이터 학습은 이루어지지 않았습니다.

LinearRegression()

In [40]:
df_age_sex = df_diabetes[['age', 'sex']]
df_age_sex.head(3)

age       sex
0  0.038076  0.050680
1 -0.001882 -0.044642
2  0.085299  0.050680

In [41]:
# dataFrame 방식
linearRegression.fit(X = df_age_sex, y = load_diabetes['target'])

# fit(): 모델을 학습시키는 함수입니다. 데이터를 사용해 모델이 학습하도록 합니다.
# X: 특성 데이터 (입력값) → load_diabetes['data']
# y: 레이블 데이터 (정답값) → load_diabetes['target']

LinearRegression()

In [42]:
linearRegression.coef_, linearRegression.intercept_
# y^ = (301.16135996 * 0.038076) + (17.3924542 * 0.050680) + 152.13348416289594

(array([301.16135996,  17.3924542 ]), 152.13348416289594)

In [43]:
predict = linearRegression.predict(df_age_sex[:1])    # 0.038076	0.050680 -> y^
source = load_diabetes['target'][:1]
predict, source

(array([164.48192757]), array([151.]))

In [44]:
(301.16135996 * 0.038076) + (17.3924542 * 0.050680) + 152.13348416289594

164.4819536835889

In [45]:
# type(df_age_sex[:1])
df_age_sex[:1]

age      sex
0  0.038076  0.05068

In [46]:
df_age_sex[:1].values, df_age_sex[:1].values.shape

(array([[0.03807591, 0.05068012]]), (1, 2))

### 모델 배포

In [47]:
# 인스턴스화 되어 있는 것을 파일로 저장
import pickle

In [48]:
save_file_name = '../../files/03.LinearRegression_deployments_diabetes.pkl'

with open(save_file_name, 'wb') as save_file :
    pickle.dump(linearRegression, save_file)
    pass