## 회귀모델 사용
- y(label, 종속변수, target)가 연속형일 때 사용 # label, 종속변수, target는 y의 명칭들

In [29]:
import sklearn as sk

### 데이터 수집

In [30]:
from sklearn import datasets

#from boston house
# datasets.load_diabetes() 
load_diabetes = datasets.load_diabetes() # 인디언 당뇨 상황 조사
load_diabetes
load_diabetes.keys() # 딕셔너리의 형태로 어떠한 key 가 들어있는지 확인

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [31]:
# feature datas 
type(load_diabetes['data']), load_diabetes['data'].shape #shape 데이터의 크기 확인

(numpy.ndarray, (442, 10))

In [32]:
# label data
type(load_diabetes['target']), load_diabetes['target'].shape, load_diabetes['target'].dtype

(numpy.ndarray, (442,), dtype('float64'))

In [33]:
# feature names
type(load_diabetes['feature_names']), load_diabetes['feature_names'], len(load_diabetes['feature_names'])

(list, ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], 10)

In [34]:
print(load_diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

### 데이터 전처리
- 결측치와 이상치 처리
- 데이터셋 분할(학습용도와 검증용도)

In [35]:
import pandas as pd

In [36]:
# feature 처리
df_diabetes = pd.DataFrame(data = load_diabetes['data']
             , columns = load_diabetes['feature_names'])
df_diabetes.head(3)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930

In [37]:
# label 처리
df_diabetes['MeasureValue'] = load_diabetes['target']

In [38]:
df_diabetes.head(3)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   

         s4        s5        s6  MeasureValue  
0 -0.002592  0.019907 -0.017646         151.0  
1 -0.039493 -0.068332 -0.092204          75.0  
2 -0.002592  0.002861 -0.025930         141.0

In [39]:
df_diabetes.shape

(442, 11)

In [40]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   age           442 non-null    float64
 1   sex           442 non-null    float64
 2   bmi           442 non-null    float64
 3   bp            442 non-null    float64
 4   s1            442 non-null    float64
 5   s2            442 non-null    float64
 6   s3            442 non-null    float64
 7   s4            442 non-null    float64
 8   s5            442 non-null    float64
 9   s6            442 non-null    float64
 10  MeasureValue  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB


In [41]:
# 학습용도와 검증용도 분할

### 데이터 학습 과정

In [42]:
from sklearn.linear_model import LinearRegression
linearRegression = LinearRegression()
linearRegression

LinearRegression()

In [43]:
# numpy 방식
linearRegression.fit(X = load_diabetes['data'], y = load_diabetes['target'])

LinearRegression()

In [44]:
# DataFrame 방식
features = df_diabetes.iloc[:, :-1]
label = df_diabetes['MeasureValue']
linearRegression.fit(X = features, y = label)

LinearRegression()

In [45]:
#모델의 성능 평가
linearRegression.score()

TypeError: score() missing 2 required positional arguments: 'X' and 'y'

### 데이터 학습 검증

In [28]:
linearRegression.score(X = load_diabetes['data'], y = load_diabetes['target'])
# scroe 함수는 모델의 예측 성능을 평가하는 함수
# 결과로 나오는 값은 **결정계수 (R-squared)**이며 0~1 사이의 값 입니다.
# 1에 가까울수록 모델이 데이터를 잘 설명하는것을 의미합니다.
# 예 0.55 라면 모델이 데이터를 55%만큼 설명한다는 뜻 입니다.

0.5177484222203498

In [30]:
# weight 동일
linearRegression.coef_, len(linearRegression.coef_)
# y = -10.0098663 * x_1 + -239.81564367 * x_2 +...+ 67.62669218 * x_10

# **가중치(Coefficient)**는 각 특성(feature)이 모델에 얼마나 영향을 미치는지를 나타냅니다.

(array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
        -792.17563855,  476.73902101,  101.04326794,  177.06323767,
         751.27369956,   67.62669218]),
 10)

In [32]:
# 데이터프레임을 만들어 각 특성(feature)과 가중치(coefficient)를 보기 쉽게 표 형태로 나타내기
pd.DataFrame(data = linearRegression.coef_, columns = ['coef_']
             , index = load_diabetes['feature_names'])


coef_
age  -10.009866
sex -239.815644
bmi  519.845920
bp   324.384646
s1  -792.175639
s2   476.739021
s3   101.043268
s4   177.063238
s5   751.273700
s6    67.626692

In [31]:
# y 절편
linearRegression.intercept_

# 절편은(intercept)은 회귀식의 y축을 만나는 값
# 절편은 모든 입력값 x_1,x_2 ... x_n 이 0일 때의 예측값
# 예 152.13이라면 모든 특성값이 0일때 예측값은 152.13

152.13348416289597

### 모델 배포

In [33]:
# 예측
# 학습된 선형 회귀 모델(linearRegression)을 사용하여 첫 5개의 데이터를 예측하기
predict_diabetes_5 = linearRegression.predict(load_diabetes['data'][:5]) # 첫 5개 예측값 생성
predict_diabetes_5



array([206.11667725,  68.07103297, 176.88279035, 166.91445843,
       128.46225834])

In [35]:
# 예측값과 비교하기 위해 실제 데이터셋의 목표값(target)을 가져오기
load_diabetes['target'][:5] # 첫 5개의 실제 값

# load_diabetes['target'][:5]는 데이터셋에 저장된 **실제 목표값(정답)** 입니다. 
# 실제값은 우리가 예측값과 비교하여 모델의 정확도를 평가하는데 사용됩니다.
# 예측값은 실제값에 근접하지만 완벽히 돌일하지는 않음, 이런차이는 모델의 성능(정확도)에 따라 달라질 수 있음


array([151.,  75., 141., 206., 135.])