## 스케일링(scaling)
- 대상 데이터 범위 조정해 모델 성능 개선

In [40]:
# 1.데이터 준비

import numpy as np

data = np.array([[1,2,3]
                 ,[4,5,6]
                 ,[7,8,9]])

data_transform = np.array([[10,20,30]
                            ,[40,50,60]
                            ,[70,80,90]])

data_differents = np.array([
    [1, 100, 0.001], # 작은 값과 매우 큰 값의 혼합 
    [50, 500, 0.005], 
    [100, 1000, 0.010], 
    [200, 2000, 0.020], 
    [400, 4000, 0.050] # 값이 점진적으로 증가 
    ])





In [41]:
data_differents.shape

(5, 3)

### StandardScaler
- 평균 0, 표준편차 1 조정하는 표준 정규분포
- 데이터가 정규분포 따를 때 적합 

In [42]:
# 2. StandardScaler 적용

from sklearn.preprocessing import StandardScaler

standardScaler = StandardScaler()
# standardScaler.fit(data) # 스케일 학습
# standardScaler.fit(data_transform) # 스케일 학습
standardScaler.fit(data_differents) # 스케일 학습

standardScaler      # 배포 공식 유지

#fit 메서드는 데이터를 분석해 평균과 표준편차를 계산합니다.

StandardScaler()

In [43]:
# 3. 변환(Transform)

# standardScaler.transform(data_transform) # 학습된 스케일 분포로 대상 분포 변환
standardScaler.transform(data_differents) # 학습된 스케일 분포로 대상 분포 변환



array([[-1.05658515, -1.01908043, -0.92104942],
       [-0.70958333, -0.73201552, -0.69362981],
       [-0.35549983, -0.37318438, -0.4093553 ],
       [ 0.35266716,  0.34447789,  0.15919373],
       [ 1.76900115,  1.77980245,  1.86484081]])

In [44]:
# 4. 새로운 데이터 변환

# 배포 및 서비스
# input : 50, 500, 0.005
standardScaler.transform([[50, 500, 0.005]])
# model 있는 경우 predict 시행

array([[-0.70958333, -0.73201552, -0.69362981]])

In [45]:
# 5. 원래 데이터로 복원(Inverse Transform)

standardScaler.inverse_transform([[-0.70958333, -0.73201552, -0.69362981]])

array([[4.99999995e+01, 5.00000003e+02, 5.00000005e-03]])